name: quiz_app_with_gemini
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  get: ^4.7.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/onboardingscreen.png"
  background_color: "#FF1F1F1F"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/title.png
    - assets/icons/

  fonts:
    - family: Bricolage
      fonts:
        - asset: assets/fonts/Bricolage.ttf

    - family: BlackItalic
      fonts:
        - asset: assets/fonts/M-BlackItalic.ttf


flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png
  android: true
  ios: true